<?php

namespace App\Http\Requests\Admin\User;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Password;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
       // dd($this->user); user table's id
        return [
            'name' => 'required|string',
            'email' => ['required','email',Rule::unique('users')->ignore($this->user)],
            'password' =>['required', 'confirmed', Password::min(8)],
            'role' => 'required|integer',
          //  'user_id' => 'required|integer|exists:users,id'
        ];

    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
